"use client";
export const createListingSlice = (set, get) => ({
  listings: [
    {
      id: 1,
      locationType: "house",
      placeType: "An entire place",
      mapData: undefined,
      locationData: undefined,
      placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
      placeAmeneties: [],
      photos: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2mI2y7tFQ6tLl58HsdJsoyEJ6D5MGi_pDEA&s",
        "https://img.vistarooms.com/gallery/compressed/idyllic-farmhouse-a-glasshouse-29e2c9.jpg",
        "https://assets.architecturaldigest.in/photos/61922845a69fa9f9fffb41cf/16:9/w_2560%2Cc_limit/delhi%2520farmhouse.png",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2023/04/Modern-farmhouse-decor-in-an-open-living-space-by-Decorilla-1024x683.jpeg?width=900",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2022/09/Modern-Farmhouse-interior-design-guide-by-Decorilla-1024x683.jpeg?width=900",
      ],
      title: "Mannat Hills",
      description:
        "SANTIPHAP ROOM - is a spacious en-suite located on the top floor of the renovated 40-year old shophouse call . The room is a Thai-contemporary inspired, overlooking one of the most sacred and a balcony with little garden.",
      price: 9000,
    },
    {
      id: 2,
      locationType: "house",
      placeType: "An entire place",
      mapData: undefined,
      locationData: undefined,
      placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
      placeAmeneties: [],
      photos: [
        "https://img.vistarooms.com/gallery/compressed/idyllic-farmhouse-a-glasshouse-29e2c9.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2mI2y7tFQ6tLl58HsdJsoyEJ6D5MGi_pDEA&s",
        "https://assets.architecturaldigest.in/photos/61922845a69fa9f9fffb41cf/16:9/w_2560%2Cc_limit/delhi%2520farmhouse.png",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2023/04/Modern-farmhouse-decor-in-an-open-living-space-by-Decorilla-1024x683.jpeg?width=900",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2022/09/Modern-Farmhouse-interior-design-guide-by-Decorilla-1024x683.jpeg?width=900",
      ],
      title: "Mannat Hills",
      description:
        "SANTIPHAP ROOM - is a spacious en-suite located on the top floor of the renovated 40-year old shophouse call . The room is a Thai-contemporary inspired, overlooking one of the most sacred and a balcony with little garden.",
      price: 6899,
    },
    {
      id: 3,
      locationType: "house",
      placeType: "An entire place",
      mapData: undefined,
      locationData: undefined,
      placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
      placeAmeneties: [],
      photos: [
        "https://assets.architecturaldigest.in/photos/61922845a69fa9f9fffb41cf/16:9/w_2560%2Cc_limit/delhi%2520farmhouse.png",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2mI2y7tFQ6tLl58HsdJsoyEJ6D5MGi_pDEA&s",
        "https://img.vistarooms.com/gallery/compressed/idyllic-farmhouse-a-glasshouse-29e2c9.jpg",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2023/04/Modern-farmhouse-decor-in-an-open-living-space-by-Decorilla-1024x683.jpeg?width=900",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2022/09/Modern-Farmhouse-interior-design-guide-by-Decorilla-1024x683.jpeg?width=900",
      ],
      title: "Mannat Hills",
      description:
        "SANTIPHAP ROOM - is a spacious en-suite located on the top floor of the renovated 40-year old shophouse call . The room is a Thai-contemporary inspired, overlooking one of the most sacred and a balcony with little garden.",
      price: 5000,
    },
    {
      id: 4,
      locationType: "house",
      placeType: "An entire place",
      mapData: undefined,
      locationData: undefined,
      placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
      placeAmeneties: [],
      photos: [
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2023/04/Modern-farmhouse-decor-in-an-open-living-space-by-Decorilla-1024x683.jpeg?width=900",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2mI2y7tFQ6tLl58HsdJsoyEJ6D5MGi_pDEA&s",
        "https://img.vistarooms.com/gallery/compressed/idyllic-farmhouse-a-glasshouse-29e2c9.jpg",
        "https://assets.architecturaldigest.in/photos/61922845a69fa9f9fffb41cf/16:9/w_2560%2Cc_limit/delhi%2520farmhouse.png",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2022/09/Modern-Farmhouse-interior-design-guide-by-Decorilla-1024x683.jpeg?width=900",
      ],
      title: "Mannat Hills",
      description:
        "SANTIPHAP ROOM - is a spacious en-suite located on the top floor of the renovated 40-year old shophouse call . The room is a Thai-contemporary inspired, overlooking one of the most sacred and a balcony with little garden.",
      price: 25000,
    },
    {
      id: 5,
      locationType: "house",
      placeType: "An entire place",
      mapData: undefined,
      locationData: undefined,
      placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
      placeAmeneties: [],
      photos: [
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2022/09/Modern-Farmhouse-interior-design-guide-by-Decorilla-1024x683.jpeg?width=900",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2mI2y7tFQ6tLl58HsdJsoyEJ6D5MGi_pDEA&s",
        "https://img.vistarooms.com/gallery/compressed/idyllic-farmhouse-a-glasshouse-29e2c9.jpg",
        "https://assets.architecturaldigest.in/photos/61922845a69fa9f9fffb41cf/16:9/w_2560%2Cc_limit/delhi%2520farmhouse.png",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2023/04/Modern-farmhouse-decor-in-an-open-living-space-by-Decorilla-1024x683.jpeg?width=900",
      ],
      title: "Mannat Hills",
      description:
        "SANTIPHAP ROOM - is a spacious en-suite located on the top floor of the renovated 40-year old shophouse call . The room is a Thai-contemporary inspired, overlooking one of the most sacred and a balcony with little garden.",
      price: 55500,
    },
    {
      id: 6,
      locationType: "house",
      placeType: "An entire place",
      mapData: undefined,
      locationData: undefined,
      placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
      placeAmeneties: [],
      photos: [
        "https://assets.architecturaldigest.in/photos/61922845a69fa9f9fffb41cf/16:9/w_2560%2Cc_limit/delhi%2520farmhouse.png",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2mI2y7tFQ6tLl58HsdJsoyEJ6D5MGi_pDEA&s",
        "https://img.vistarooms.com/gallery/compressed/idyllic-farmhouse-a-glasshouse-29e2c9.jpg",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2023/04/Modern-farmhouse-decor-in-an-open-living-space-by-Decorilla-1024x683.jpeg?width=900",
        "https://cdn.decorilla.com/online-decorating/wp-content/uploads/2022/09/Modern-Farmhouse-interior-design-guide-by-Decorilla-1024x683.jpeg?width=900",
      ],
      title: "Mannat Hills",
      description:
        "SANTIPHAP ROOM - is a spacious en-suite located on the top floor of the renovated 40-year old shophouse call. The room is a Thai-contemporary inspired, overlooking one of the most sacred and a balcony with little garden.",
      price: 8200,
    },
  ],
  isMapView: false,
  userListings: [],
  wishLists: [],
  // wishListsPage: [],

  setListings: (listings) => set({ listings }),
  setIsMapView: () => set({ isMapView: !get().isMapView }),
  setUserListings: (userListings) => set({ userListings }),
  setWishLists: (wishLists) => set({ wishLists }),
  // setWishListsPage: (wishListsPage) => set({ wishListsPage }),
});
