export const createListingSlice = (set, get) => ({
  listings: [],
  isMapView: false,
  userListings: [],
  wishLists: [],
  currentListing: undefined,
  createNewListing: undefined,
  imageListings: [],
  setListings: (listings) => set({ listings }),
  setIsMapView: () => set({ isMapView: !get().isMapView }),
  setUserListings: (userListings) => set({ userListings }),
  setWishLists: (wishLists) => set({ wishLists }),
  setCurrentListing: (listing) => set({ currentListing: listing }),
  setCreateNewListing: (createNewListing) => set({ createNewListing }),
  setImageListings: (imageListings) => set({ imageListings }),
});
