export const createProcessSlice = (set, get) => ({
  address1: "",
  address2: "",
  address3: "",
  landMark: "",
  city: "",
  state: "",
  country: "",
  pinCode: "",
  no_Bathroom: 1,
  no_BedRoom: 1,
  no_Guest: 4,
  photos: [],
  farm_Name: "",
  farm_Description: "",
  farm_BookingPrice: 0,
  amenitie: [
    {
      operation: "i",
      farmHouseCode: "",
      wifi: false,
      tv: false,
      kitchen: false,
      washingMachine: false,
      freeParking: false,
      paidParking: false,
      airConditioner: false,
      dedicatedWorkout: false,
      swimmingPool: false,
      hotTub: false,
      patio: false,
      bbqGrill: false,
      outdoorDinningArea: false,
      firePit: false,
      poolTable: false,
      indoorFireplace: false,
      piano: false,
      exerciseEquipment: false,
      lakeAccess: false,
      beachAccess: false,
      skiIn_SkiOut: false,
      outdoorShower: false,
      smokeAlarm: false,
      firstAidKit: false,
      fireExtinguisher: false,
      carbonMonoOxideAlarm: false,
      createdBy: "",
    },
  ],
  farmHouseCode: undefined,
  task: "i",
  columnName: undefined,
  updateValues: undefined,
  setAddress1: (address1) => set({ address1 }),
  setAddress2: (address2) => set({ address2 }),
  setAddress3: (address3) => set({ address3 }),
  setLandmark: (landMark) => set({ landMark }),
  setCity: (city) => set({ city }),
  setState: (state) => set({ state }),
  setCountry: (country) => set({ country }),
  setPincode: (pinCode) => set({ pinCode }),
  setBathroom: (no_Bathroom) => set({ no_Bathroom }),
  setBedRoom: (no_BedRoom) => set({ no_BedRoom }),
  setGuest: (no_Guest) => set({ no_Guest }),
  setFarmName: (farm_Name) => set({ farm_Name }),
  setFarmDescription: (farm_Description) => set({ farm_Description }),
  setFarmBookingPrice: (farm_BookingPrice) => set({ farm_BookingPrice }),
  setAmenitie: (amenitie) => set({ amenitie }),
  setPhotos: (photos) => set({ photos }),
  setFarmHouseCode: (farmHouseCode) => set({ farmHouseCode }),
  setTask: (task) => set({ task }),
  setColumnName: (columnName) => set({ columnName }),
  setUpdateValues: (updateValues) => set({ updateValues }),
});

// {
//   "farm_Name": "string",
//   "farm_Description": "string",
//   "farm_BookingPrice": 0,
//   "address1": "string",
//   "address2": "string",
//   "address3": "string",
//   "landMark": "string",
//   "city": "string",
//   "state": "string",
//   "country": "string",
//   "pinCode": "string",
//   "no_Bathroom": 0,
//   "no_BedRoom": 0,
//   "no_Guest": 0,
//   "amenities": "string",
//   "farmHouseCode": "string",
//   "task": "string",
//   "columnName": "string",
//   "updateValues": "string"
// }

// export const createProcessSlice = (set, get) => ({
//   locationType: undefined,
//   placeType: undefined,
//   mapData: undefined,
//   locationData: undefined,
//   placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
//   placeAmeneties: [],
//   photos: [],
//   title: "",
//   description: "",
//   price: 0,
//   setLocationType: (locationType) => set({ locationType }),
//   setPlaceType: (placeType) => set({ placeType }),
//   setMapData: (mapData) => set({ mapData }),
//   setLocationData: (locationData) => set({ locationData }),
//   setPlaceSpace: (placeSpace) => set({ placeSpace }),
//   setPlaceAmeneties: (placeAmeneties) => set({ placeAmeneties }),
//   setPhotos: (photos) => set({ photos }),
//   setTitle: (title) => set({ title }),
//   setDescription: (description) => set({ description }),
//   setPrice: (price) => set({ price }),
// });
