export const createProcessSlice = (set, get) => ({
  address1: "",
  address2: "",
  address3: "",
  landMark: "",
  city: "",
  state: "",
  country: "",
  pinCode: "",
  noBathroom: 1,
  noBedRoom: 1,
  noGuest: 4,
  noAdults: 0,
  noChildren: 0,
  noInfants: 0,
  noPets: 0,
  farmName: "",
  farmDescription: "",
  farmBookingPrice: 0,
  amenities: [
    {
      wifi: false,
      tv: false,
      kitchen: false,
      washingMachine: false,
      freeParking: false,
      paidParking: false,
      airConditioner: false,
      dedicatedWorkout: false,
      swimmingPool: false,
      hotTub: false,
      patio: false,
      bbqGrill: false,
      outdoorDinningArea: false,
      firePit: false,
      poolTable: false,
      indoorFireplace: false,
      piano: false,
      exerciseEquipment: false,
      lakeAccess: false,
      beachAccess: false,
      skiIn_SkiOut: false,
      outdoorShower: false,
      smokeAlarm: false,
      firstAidKit: false,
      fireExtinguisher: false,
      carbonMonoOxideAlarm: false,
    },
  ],
  // farmStatus: "active",
  taskType: "ins",
  // columnName: undefined,
  // updateValues: undefined,
  setAddress1: (address1) => set({ address1 }),
  setAddress2: (address2) => set({ address2 }),
  setAddress3: (address3) => set({ address3 }),
  setLandmark: (landMark) => set({ landMark }),
  setCity: (city) => set({ city }),
  setState: (state) => set({ state }),
  setCountry: (country) => set({ country }),
  setPincode: (pinCode) => set({ pinCode }),
  setBathroom: (noBathroom) => set({ noBathroom }),
  setBedRoom: (noBedRoom) => set({ noBedRoom }),
  setGuest: (noGuest) => set({ noGuest }),
  setAdults: (noAdults) => set({ noAdults }),
  setChildren: (noChildren) => set({ noChildren }),
  setInfants: (noInfants) => set({ noInfants }),
  setPets: (noPets) => set({ noPets }),
  setFarmName: (farmName) => set({ farmName }),
  setFarmDescription: (farmDescription) => set({ farmDescription }),
  setFarmBookingPrice: (farmBookingPrice) => set({ farmBookingPrice }),
  setAmenities: (amenities) => set({ amenities }),
  // setFarmStatus: (farmStatus) => set({ farmStatus }),
  setTaskType: (taskType) => set({ taskType }),
  // setColumnName: (columnName) => set({ columnName }),
  // setUpdateValues: (updateValues) => set({ updateValues }),
});

// export const createProcessSlice = (set, get) => ({
//   locationType: undefined,
//   placeType: undefined,
//   mapData: undefined,
//   locationData: undefined,
//   placeSpace: { bathrooms: 1, beds: 1, guest: 4 },
//   placeAmeneties: [],
//   photos: [],
//   title: "",
//   description: "",
//   price: 0,
//   setLocationType: (locationType) => set({ locationType }),
//   setPlaceType: (placeType) => set({ placeType }),
//   setMapData: (mapData) => set({ mapData }),
//   setLocationData: (locationData) => set({ locationData }),
//   setPlaceSpace: (placeSpace) => set({ placeSpace }),
//   setPlaceAmeneties: (placeAmeneties) => set({ placeAmeneties }),
//   setPhotos: (photos) => set({ photos }),
//   setTitle: (title) => set({ title }),
//   setDescription: (description) => set({ description }),
//   setPrice: (price) => set({ price }),
// });
