// import { Geist, Geist_Mono } from "next/font/google";

import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import NavigationEvents from "@/components/common/NavigationEvents";

import { useAppStore } from "@/store/store";
import ModalWrapper from "@/components/common/ModalWrapper";

const inter = Inter({ subsets: ["latin"] });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Pastoral Paradise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        href="https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css"
        rel="stylesheet"
        precedence="default"
      />
      <link
        rel="stylesheet"
        href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.2/mapbox-gl-geocoder.css"
        type="text/css"
        precedence="default"
      />
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        className={inter.className}
        cz-shortcut-listen="true"
      >
        <ModalWrapper/>
        {children}
      
        {/* <Suspense fallback={null}>
          <NavigationEvents />
        </Suspense> */}
      </body>
    </html>
  );
}
